---
driver:
  name: ec2
  region: us-west-2
  subnet_id: subnet-632b1404
  security_group_ids: ["sg-c00149ba"]
  aws_ssh_key_id: Kubernetes
#  iam_profile_name: s3accesstoec2
  tags:
    Owner: nikhil.kapure
    Environment: Testing
    Project: reanassess

transport:
  ssh_key: C:\Users\OPEX\Desktop\Kubernetes.pem

verifier:
  name: inspec

platforms:
  # CentOS 7
  - name: Ubuntu16
    driver:
      image_id: ami-0071dd60
      instance_type: t2.medium
      #spot_price: 0.5
      tags:
        Name: kubernetes-Fedora25
suites:
  - name: default
    run_list:
      - recipe[kubernetes-cluster::default]
    attributes:
      kubernetes-cluster:
        agent: worker
        ipaddress: "10.0.11.158"
        token: "3e91d9.e0a03180686b4dde"
        user-name: "fedora"